// Copyright (c) 2025 CNRS
// Author: Florent Lamiraux
//

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.

#ifndef HPP_COVERAGE_CORBA_PATH_HH
#define HPP_COVERAGE_CORBA_PATH_HH

#include <hpp/common.idl>
#include <hpp/core_idl/paths.idl>
#include <hpp/core_idl/path_planners.idl>
#include <hpp/pinocchio_idl/robots.idl>

module hpp {
  module corbaserver {
    module coverage {
      interface Path {
        /// \{
        /// Path modification
	///
	/// Multiply two paths with value in SE(3)
	/// \param p1, p2 paths to be multiplied
	/// \return the resutl of the multiplication.
        hpp::core_idl::Path multiply(in hpp::core_idl::Path p1, in hpp::core_idl::Path p2)
	  raises(Error);
	/// Create a spline path with values in SE(3)
	///
	/// \param pose0, pose1, initial and final values of the path,
	/// \param length length of the interval of definition,
	/// \param order order of continuity of the derivatives: 0 linear interpolation,
	///        1 polynomial of degree 3 with zero velocities at beginning and end.
	hpp::core_idl::Path createSpline(in hpp::floatSeq pose0, in hpp::floatSeq pose1,
					 in double length, in unsigned long order)
	  raises(Error);
	/// Set cost in Roadmap
	///
	/// Set hpp::coverage::Cost as the cost in the given roadmap
	void setCost(in hpp::core_idl::Roadmap roadmap, in hpp::pinocchio_idl::Device robot,
		     in string gripperName)
	  raises(Error);
        /// \}
      };
    }; // interface Path
  }; // module coverage
}; // module hpp

#endif // HPP_COVERAGE_CORBA_COVERAGE_HH
